# Generated by Django 3.2 on 2022-03-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'actor'), ('writer', 'writer'), ('direrctor', 'director')], max_length=10, null=True, verbose_name='role'),
        ),
    ]
