# Generated by Django 3.2 on 2022-03-29 03:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_filmwork_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
